# Generated by Django 5.1.3 on 2024-12-18 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Token',
            new_name='SpotifyAccessToken',
        ),
    ]
