# Generated by Django 5.1.3 on 2024-12-10 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
